version: "3.9"

services:
  postgres-catalog:
    image: postgres:16-alpine
    env_file: .env
    environment: POSTGRES_DB: ${POSTGRES_DB_CATALOG}
    volumes: - catalog_data:/var/lib/postgresql/data
    networks: - lib-net

  postgres-user:
    image: postgres:16-alpine
    env_file: .env
    environment: POSTGRES_DB: ${POSTGRES_DB_USER}
    volumes: - user_data:/var/lib/postgresql/data
    networks: - lib-net

  postgres-lending:
    image: postgres:16-alpine
    env_file: .env
    environment: POSTGRES_DB: ${POSTGRES_DB_LENDING}
    volumes: - lending_data:/var/lib/postgresql/data
    networks: - lib-net

  postgres-digital:
    image: postgres:16-alpine
    env_file: .env
    environment: POSTGRES_DB: ${POSTGRES_DB_DIGITAL}
    volumes: - digital_data:/var/lib/postgresql/data
    networks: - lib-net

  gateway:
    build: ./gateway/nginx
    ports: - "${GATEWAY_PORT}:80"
    depends_on: [catalog-service, user-service, lending-service, digital-service]
    networks: - lib-net

  catalog-service:
    build: ./services/catalog-service
    env_file: .env
    depends_on: [postgres-catalog]
    networks: - lib-net

  user-service:
    build: ./services/user-service
    env_file: .env
    depends_on: [postgres-user]
    networks: - lib-net

  lending-service:
    build: ./services/lending-service
    env_file: .env
    depends_on: [postgres-lending]
    networks: - lib-net

  digital-service:
    build: ./services/digital-service
    env_file: .env
    depends_on: [postgres-digital]
    networks: - lib-net

networks:
  lib-net:
    driver: bridge

volumes:
  catalog_data:
  user_data:
  lending_data:
  digital_data: