worker_processes auto;

events { worker_connections 1024; }

http {
    upstream catalog { server catalog-service:8001; }
    upstream user { server user-service:8002; }
    upstream lending { server lending-service:8003; }
    upstream digital { server digital-service:8004; }

    server {
        listen 80;
        server_name localhost;

        location /api/catalog/ {
            proxy_pass http://catalog/api/catalog/;
            proxy_set_header Host $host;
        }
        location /api/users/ {
            proxy_pass http://user/api/users/;
            proxy_set_header Host $host;
        }
        location /api/lending/ {
            proxy_pass http://lending/api/lending/;
            proxy_set_header Host $host;
        }
        location /api/digital/ {
            proxy_pass http://digital/api/digital/;
            proxy_set_header Host $host;
        }
    }
}