"""initial_migration

Revision ID: 6b4a114a40e9
Revises: 
Create Date: 2026-05-06 21:13:23.194451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4a114a40e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('file_size_mb', sa.Integer(), nullable=False),
    sa.Column('license_type', sa.String(length=50), nullable=False),
    sa.Column('drm_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_assets_book_id'), 'digital_assets', ['book_id'], unique=False)
    op.create_index(op.f('ix_digital_assets_id'), 'digital_assets', ['id'], unique=False)
    op.create_table('access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['digital_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_tokens_id'), 'access_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_access_tokens_loan_id'), 'access_tokens', ['loan_id'], unique=False)
    op.create_index(op.f('ix_access_tokens_token'), 'access_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_tokens_token'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_loan_id'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_id'), table_name='access_tokens')
    op.drop_table('access_tokens')
    op.drop_index(op.f('ix_digital_assets_id'), table_name='digital_assets')
    op.drop_index(op.f('ix_digital_assets_book_id'), table_name='digital_assets')
    op.drop_table('digital_assets')
    # ### end Alembic commands ###
