"""initial_migration

Revision ID: 848526f7702a
Revises: 
Create Date: 2026-05-06 21:16:24.112320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848526f7702a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_copy_id', sa.Integer(), nullable=False),
    sa.Column('digital_asset_id', sa.Integer(), nullable=True),
    sa.Column('loan_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', 'CANCELLED', name='loanstatus'), nullable=False),
    sa.Column('loan_type', sa.Enum('PHYSICAL', 'DIGITAL', name='loantype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_loans_status_due_date', 'loans', ['status', 'due_date'], unique=False)
    op.create_index('idx_loans_user_loan_date', 'loans', ['user_id', 'loan_date'], unique=False)
    op.create_index(op.f('ix_loans_book_copy_id'), 'loans', ['book_copy_id'], unique=False)
    op.create_index(op.f('ix_loans_digital_asset_id'), 'loans', ['digital_asset_id'], unique=False)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_user_id'), 'loans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_digital_asset_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_book_copy_id'), table_name='loans')
    op.drop_index('idx_loans_user_loan_date', table_name='loans')
    op.drop_index('idx_loans_status_due_date', table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
